# Generated by Django 4.0.2 on 2022-04-23 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_custom_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='custom',
            name='profile_pic',
            field=models.ImageField(blank=True, default='profile1.png', null=True, upload_to=''),
        ),
    ]
